### ISSUE TITLE
JOSS Review: Automated Testing

### ISSUE THREAD

**Issue by gchure** [baiyueh/PANINIpy#4]
Hi! I'm reviewing your paper for [JOSS](https://github.com/openjournals/joss-reviews/issues/7312) and am opening issues as I go through my checklist. 

This package does not appear to have any testing, which is a pretty big blocking omission. If you do have tests in your local development, please add and commit them into the repository and set them up for continuous integration.

Happy to discuss this more, but this is a critical issue to address to continue with the review.

**Comment by baiyueh** [comment]
Hi @gchure, the test section with pytest has been added for both insturction for local [Testing and Continuous Integration](https://paninipy.readthedocs.io/en/latest/Papers/installation.html), and CI flow on GitHub [workflow](https://github.com/baiyueh/PANINIpy/actions). Please let us know if this could resolve your issue, thanks!

**Comment by gchure** [comment]
Great, thank you! I cloned the repository to run the tests and encountered some issues with installation. I was able to resolve them by fixing some issues in your `setup.py`.

To run the tests, I created a virtual environment on my local machine running python 3.11 and installed paninipy via `pip install -e .`. Doing so installed the package, but it could not be imported as `import paninipy`. This is because your `setup.py` file says the package name is `paninipy`, but your module directlry is `PANINIpy`. Running `import PANINIpy` ran without issue. 

I would suggest changing the root folder to be `paninipy` (all lower caps) to be consistent with the documentation and tests. 

Also, there's a small typo in your `setup.py`. The field `project_urls` is mistyped as `projects_urls`.

**Comment by gchure** [comment]
Otherwise, the tests all seem to run, so once the naming convention is addressed you can close this issue.

**Comment by baiyueh** [comment]
Hi @gchure, I have run the test node with Python 3.11 without any issues, and I believe the package naming issue was resolved previously. Could you please check the version of paninipy by running `pip show paninipy`? If it is below 1.0, you will need to either reinstall it using `pip uninstall paninipy --yes` followed by `pip install paninipy`, or simply update the current version with `pip install --upgrade paninipy` to resolve the issue.

Thanks, just fixed the typo thing in `setup.py`.

**Comment by gchure** [comment]
Okay, interesting. I'm still getting it to fail locally when I install paninipy from source (cloning the repo and then running `pip install -e)`. I get the same result if I do `pip install paninipy`

Here's the output of `pip show paninipy`: 

```
Name: paninipy
Version: 1.1
Summary: Package of Algorithms for Nonparametric Inference with Networks in Python
Home-page: https://paninipy.readthedocs.io/en/latest/index.html
Author: Baiyue He
Author-email: baiyue.he@connect.hku.hk
License: The MIT License
Location: /Users/gchure/Desktop/paninipy
Requires: numpy, pandas, scipy
Required-by:
```

The result of `pip freeze` in my venv yields the following:

```
numpy==2.1.3
pandas==2.2.3
paninipy==1.1
python-dateutil==2.9.0.post0
pytz==2024.2
scipy==1.14.1
six==1.16.0
tzdata==2024.2
```

With this (and having pulled the most recent commit of the repo), running `pytest` from the root directory fails with the following:
[paninipy_failure.txt](https://github.com/user-attachments/files/17668379/paninipy_failure.txt)

This is fixed by simply running `mv PANINIpy paninipy && pytest` with the following output:
[paninipy_success.txt](https://github.com/user-attachments/files/17668392/paninipy_success.txt)

My local environment is MacOS with OS Sonoma 14.6.1.

**Comment by baiyueh** [comment]
> Okay, interesting. I'm still getting it to fail locally when I install paninipy from source (cloning the repo and then running `pip install -e)`. I get the same result if I do `pip install paninipy`
> 
> Here's the output of `pip show paninipy`:
> 
> ```
> Name: paninipy
> Version: 1.1
> Summary: Package of Algorithms for Nonparametric Inference with Networks in Python
> Home-page: https://paninipy.readthedocs.io/en/latest/index.html
> Author: Baiyue He
> Author-email: baiyue.he@connect.hku.hk
> License: The MIT License
> Location: /Users/gchure/Desktop/paninipy
> Requires: numpy, pandas, scipy
> Required-by:
> ```
> 
> The result of `pip freeze` in my venv yields the following:
> 
> ```
> numpy==2.1.3
> pandas==2.2.3
> paninipy==1.1
> python-dateutil==2.9.0.post0
> pytz==2024.2
> scipy==1.14.1
> six==1.16.0
> tzdata==2024.2
> ```
> 
> With this (and having pulled the most recent commit of the repo), running `pytest` from the root directory fails with the following: [paninipy_failure.txt](https://github.com/user-attachments/files/17668379/paninipy_failure.txt)
> 
> This is fixed by simply running `mv PANINIpy paninipy && pytest` with the following output: [paninipy_success.txt](https://github.com/user-attachments/files/17668392/paninipy_success.txt)
> 
> My local environment is MacOS with OS Sonoma 14.6.1.

**Comment by baiyueh** [comment]
Hi @gchure, thanks for providing the

**Comment by baiyueh** [comment]
Hi @gchure, thanks for providing a detailed description of the error occurrence, which helped me locate the root cause.

It turns out that my local environment is on Windows, where the file system is not case-sensitive, causing git to ignore renames that only change casing. The same applied to my local test runs. The issue it that the `pytest` imports specifically from the `paninipy` folder, which caused a mismatch due to case sensitivity. This is unrelated to the installation method (`pip install paninipy` or `pip install -e .`).

I have made the necessary adjustments to enforce lowercase usage. Here is the updated flow I followed for your reference:  
[test_env_flow.txt](https://github.com/user-attachments/files/17673031/test_env_flow.txt)

Please check it out and let me know if the issue is resolved. Thank you!

**Comment by gchure** [comment]
Great, now everything works. Thanks for working through it (I learned something new here).
